language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
  - "3.7"
  - "3.8"

env:
  global:
    - COVERALLS_PARALLEL=true
services:
  - xvfb
install:
  # ensure that we have the full tag information available for version.py
  - git fetch --unshallow --tags
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda install -q conda
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # create environment and install dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda env update -n test-environment -f environment.yml
  - source activate test-environment
  # grab newest pyuvdata just in case
  - pip install git+https://github.com/RadioAstronomySoftwareGroup/pyuvdata.git
  # install a few extras that we need for tests
  - conda install matplotlib coveralls pycodestyle pydocstyle
  - conda list
before_script:
  - python -c "from pyuvdata import version; version.main()"
script:
  - pytest --cov-report xml:./coverage.xml --cov-report term
  - pycodestyle
  - pydocstyle hera_qm/*.py --convention=numpy
after_success:
  - coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
