name: hera_qm
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy>=1.23
  - pip
  - astropy>=5.0.4
  - h5py>=3.1
  - pyuvdata>=2.3
  - scipy
  - pytest
  - scikit-learn # from hera_cal
  - pytest-cov
  - pyyaml
  - hera-filters
  - pip:
    - git+https://github.com/HERA-Team/uvtools
    - git+https://github.com/HERA-Team/hera_cal
