name: hera_qm
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy>=1.10
  - pip
  - astropy>=2.0.16
  - h5py
  - pyuvdata
  - scipy
  - pytest
  - scikit-learn # from hera_cal
  - pytest-cov
  - pip:
    - git+https://github.com/HERA-Team/hera_cal
