name: hera_qm
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy>=1.23
  - pip
  - astropy>=5.0.4
  - h5py>=3.9
  - pyuvdata>=2.3
  - scipy
  - pytest
  - pytest-cov
  - pyyaml
  - pip:
    - hera-calibration
    - uvtools
    - hera-filters
