name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  tests:
    name: Tests
    env:
      ENV_NAME: hera_qm_tests
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9, '3.10', "3.11", "3.12"]
      fail-fast: false

    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 1
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        pip install --upgrade pip
        pip install .[tests]

    - name: Run Tests
      run: |
        pytest --cov-report xml:./coverage.xml

    - name: Upload Coverage (Ubuntu)
      if: matrix.os == 'ubuntu-latest' && success()
      run: |
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
