name: Run Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Ubuntu Tests
    env:
      ENV_NAME: hera_qm_tests
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: Get Miniconda
      if: matrix.os == 'ubuntu-latest'
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh;
        bash $HOME/miniconda.sh -b -p $HOME/miniconda

    - name: Setup Environment
      run: |
        export PATH="$HOME/miniconda/bin:$PATH"
        ./ci/install_conda.sh


    - name: Install
      run: |
        export PATH="$HOME/miniconda/bin:$PATH"
        source activate ${ENV_NAME}
        pip install .

    - name: Run Tests
      run: |
        export PATH="$HOME/miniconda/bin:$PATH"
        source activate $ENV_NAME
        pytest --cov-report xml:./coverage.xml --cov-report term
        pycodestyle
        pydocstyle hera_qm/*.py --convention=numpy
        coveralls

    - name: Coverall Parallel
      uses: coverallsapp/github-action@master
      if: matrix.os == 'ubuntu-latest' && success()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true

    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
